module.exports = {
  "description":"User information object",
  "type":"object",
  "properties" : {
    "receipt_id":{
      "description":"Receipt's id",
      "type": ["integer","string"],
    },
    "user_id":{
      "description":"Receipt's owner id, this is generated by server",
      "type":"string"
    },
    "files":{
      "description":"Files attached to receipt",
      "type":"array"
    },
    "tags":{
      "description":"Receipt's tags, just a user defined string",
      "type":"array"
    },
    "name": {
      "description": "Receipt's name",
      "type": "string"
    },
    "registered": {
      "description": "Receipt's registeration date",
      "type": ["string", "null"]
    },
    "purchaseDate": {
      "description": "Receipt's purchase date",
      "type": ["string", "null"]
    },
    "warrantlyEndDate": {
      "description": "Receipt's warrantly last date",
      "type": ["string", "null"]
    },
    "store": {
      "description": "Item purchase place",
      "type": ["string", "null"]
    },
    "description": {
      "description": "Description that can be written in markdown",
      "type": ["string", "null"]
    },
    "price": {
      "description": "Item price",
      "type": ["string", "null"]
    },
    "createdBy": {
      "description": "Who created the model at first place",
      "type": ["string","integer"]
    },
    "createdOn": {
      "description": "When a model was created",
      "type": ["string"]
    },
    "updatedBy": {
      "description": "Who updated the model last time",
      "type": ["string"]
    },
    "updatedOn": {
      "description": "When a model was last updated",
      "type": ["string"]
    }
  }
};
