module.exports = {
  "description":"User information object",
  "additionalProperties": false,
  "type":"object",
  "properties" : {
    "id":{
      "description":"Receipt's id",
      "type":"string",
    },
    "user_id":{
      "description":"Receipt's owner id, this is generated by server",
      "type":"string"
    },
    "files":{
      "description":"Files attached to receipt",
      "type":"array"
    },
    "tags":{
      "description":"Receipt's tags, just a user defined string",
      "type":"array"
    },
    "name": {
      "description": "Receipt's name",
      "type": "string"
    },
    "registered": {
      "description": "Receipt's registeration date",
      "type": "string"
    },
    "purchaseDate": {
      "description": "Receipt's purchase date",
      "type": "string"
    },
    "warrantlyEndDate": {
      "description": "Receipt's warrantly last date",
      "type": "string"
    },
    "store": {
      "description": "Item purchase place",
      "type": "string"
    },
    "description": {
      "description": "Description that can be written in markdown",
      "type": "string"
    },
    "price": {
      "description": "Item price",
      "type": "string"
    }
  }
};
