module.exports = {
  "description":"Tag is a markign used in receipts object",
  "additionalProperties": false,
  "type":"object",
  "properties" : {
    "tagId":{
      "description":"Id is generated by server",
      "type":["integer", "string"]
    },
    "receiptId":{
      "description":"Id is generated by server",
      "type":["integer", "string"],
      "required": true
    },
    "name": {
      "type": "string",
      "required": true
    },
    "createdBy": {
      "description": "Who created the model at first place",
      "type": ["string","integer"]
    },
    "createdOn": {
      "description": "When a model was created",
      "type": ["string"]
    },
    "updatedBy": {
      "description": "Who updated the model last time",
      "type": ["string"]
    },
    "updatedOn": {
      "description": "When a model was last updated",
      "type": ["string"]
    }
  }
};
