module.exports = {
  "description":"User information object",
  "additionalProperties": false,
  "type":"object",
  "properties" : {
    "id":{
      "description":"Id is generated by server",
      "type":"string",
      "required": true
    },
    "username": {
      "type": "string",
      "required": true
    },
    "lang":{
      "required": true,
      "enum":["fi","en"]
    }
  }
};
